---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - name: tinyproxy
        image: agolubinskiys/tinyproxy-server:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
          - name: ALLOWED_IPS
            value: "127.0.0.1,172.16.91.100"
          - name: BASIC_AUTH
            value: "true"
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: tinyproxy-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: tinyproxy-secret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: tinyproxy-service
spec:
  selector:
    app: tinyproxy
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: tinyproxy-secret
type: Opaque
data:
  username: base64_encoded_username
  password: base64_encoded_password

